### PR TITLE
Store external favicons in localStorage

### LINKED ISSUE #2: Add External Favicon Preloading Logic
Within the [usePleaseStay] code there is a TODO to add preload logic for external favicons. You may notice when opting to take external favicons, the favicons sometimes take a moment to appear when being swapped, as they are loaded directly from the URL, and not a local asset.

To fix this, the following should be possible:

- On hook mount, for each _external_ favicon provided, the favicon should be 'downloaded' and stored somehow
    - perhaps in LocalStorage
    - perhaps in a cookie
    - perhaps even appended and hidden into the DOM somewhere - though this wouldn't work as well for static sites with multiple pages)
    - note this requires determining in the first place if the favicon is external - a regex may do nicely here

I'm open to any options, as long as it gets the job done and is not overly complex!

### PR DESCRIPTION
**Pull request by Gee19**
🎃 work in progress but open to feedback

will hopefully resolve #2

### CODE REVIEW

**Review by princefishthrower — CHANGES_REQUESTED** [review]
This looks like a nice way to store them. I'd say you're nearly there. Now it's just a matter of setting the `faviconRef.current.href` to the base64 string you've stored. Keep in mind they should be merged back into the `faviconURIs` since it is possible for a user to mix both local and external favicon URIs. Can you try and add this? Also, what is `draw the rest of the owl`?

One small other thing. I think it's time we start creating util functions. Can you create a `util` folder under `src` and then a single file and export your `convertToBase64` function from it? Also add the type annotation to `externalFaviconURI`, when you do so i.e. `(externalFaviconURI: string) => ...`

Let me know how it goes! This will be a great addition to the hook!

**Comment by Gee19** [comment]
@princefishthrower thanks for the comment, I'll tackle the stuff you mentioned soon. Also the owl comment is from a stupid meme.. I didn't sleep much the night I wrote this lol

**Comment by princefishthrower** [comment]
Screen Shot 2021-10-02 at 23 38 06

@Gee19 haha I remember now 😂 I've seen that one!

**Comment by Gee19** [comment]
Still needs to be tested but I implemented the requested changes.

**Comment by Gee19** [comment]
Would you be open to formatting stuff with `prettier` if I opened a separate PR?

**Comment by princefishthrower** [comment]
@Gee19 - did you at least smoke test it? Does it "work"? Feel free to add `prettier` in a separate PR as well!

**Comment by Gee19** [comment]
> @Gee19 - did you at least smoke test it? Does it "work"? Feel free to add `prettier` in a separate PR as well!

My initial pass was working when I tested it in isolation. I haven't been able to test the new changes. I'll come back to this tomorrow

**Comment by Gee19** [comment]
I don't believe this approach will work because of CORS :(

**Pull request closed without merging**
