### PR TITLE
Dark Mode Toggle Implmentation

### PR DESCRIPTION
**Pull request by AbhimanyuBahree**

### CODE REVIEW

**Comment by babu1998** [comment]
Screenshot 2021-10-02 at 7 20 56 PM

**Comment by babu1998** [comment]
Screenshot 2021-10-02 at 7 21 24 PM

**Review by princefishthrower — CHANGES_REQUESTED** [review]
Hi @babu1998 - this looks pretty good! Could you just move the toggle into a <nav> component (which would also need to be built)? Just use the classes and styling from one of the many bootstrap examples, perhaps the "brand" one would be super easy to put in:

https://getbootstrap.com/docs/4.0/components/navbar/#brand

Bootstrap styles and tooling are already included in the `example` part of the repository.

**Comment by babu1998** [comment]
Done I have added the brand component in index.html. You can see in my commit.

**Comment by princefishthrower** [comment]
@babu1998 nice work! Merged.

**Pull request merged**
